# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae61a3e638a2ae4e1d690818aa84bf0564cc1285934ebefff3b76af81776b55e11033621b4124ce974e1bdd3a7c9a3baf404a07c49109a1bcb0b3fbda591e3b2

test:
  secret_key_base: 3e17fb9f1363610ad1461461892bae8a8aac46ea888b0b42a32d2334c343ec8de7cd53b459e9ac281fc9ab500d7ede438160d5ac67eeeea40f3851b10265cb75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
